Repository dddstudy/ddd-web, pull requests merged in 2024-12, with the labels that each got.

#18 fix: npm audit fix를 통한 packages의 vulnerability 해결
  package-lock.json
Labels: bug, enhancement

#19 fix: FAQ 페이지 디자인 QA 사항 개선
  src/app/faq/page.tsx
  src/app/styles/screens.ts
  src/components/Accordion/index.tsx
  src/components/Navigation/DesktopNavigation.tsx
  src/components/Navigation/MobileNavigation.tsx
  src/hooks/useMediaQuery.ts
Labels: qa

#21 fix: useMediaQuery로 인한 컴포넌트 렌더링 오류 해결
  src/app/faq/page.tsx
  src/components/Navigation/index.tsx
  src/hooks/useMediaQuery.ts
Labels: bug

#23 feat: 여러 개의 Accordion 컴포넌트가 있을 때 오직 하나만 열리도록 AccordionGroup을 추가
  src/app/faq/page.tsx
  src/components/Accordion/index.stories.tsx
  src/components/Accordion/index.tsx
Labels: enhancement

#25 fix: 시스템에서 다크 모드 설정 시 텍스트 색상이 다르게 나오는 문제 해결
  src/app/globals.css
Labels: bug

#28 feat: 푸터 컴포넌트 추가
  src/app/layout.tsx
  src/app/styles/screens.ts
  src/components/Layout/Footer.tsx
Labels: enhancement

#30 feat: 모집 알람 api 연결
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  README.md
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/app/layout.tsx
  src/components/Navigation/DesktopNavigation.tsx
  src/components/Navigation/MobileNavigation.tsx
  src/components/Notification/Form.tsx
  src/components/Notification/NotificationRegisterPopup.stories.tsx
  src/fixtures/navigationList.json
  src/hooks/usePostNotification.ts
  src/mocks/browser.ts
  src/mocks/handler.ts
  src/mocks/initMock.ts
  src/mocks/provider.tsx
  src/store/notification/action.ts
  src/types/response.ts
  src/utils/http.ts
Labels: enhancement
